/**
 * Finds the language pairs worth a "you already know some of this" page, and
 * the words that make the claim true.
 *
 *   node scripts/wordlists/build-pairs.ts
 *
 * The measure is deliberately strict: a word counts only if it is spelled
 * identically in both languages AND both lists give it the same English
 * meaning. Spelling alone is a trap — Turkish and Spanish share fifty spellings
 * in their first two thousand words (ve, mi, de, o) and none of them mean the
 * same thing. Requiring the meaning to match too takes that pair from a
 * misleading 50 down to an honest 2, and leaves Czech/Slovak at 256.
 *
 * This is not a cognate list. Two languages can arrive at the same spelling
 * and sense by borrowing from a third, which is exactly what "bomba" and
 * "tren" are, and the page says as much.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '../..');
const DATA = path.join(ROOT, 'static/data/most-common-words');
const OUT = path.join(DATA, 'pairs');

/** Only the commonest words: a shared rarity is not a head start. */
const DEPTH = 2000;
/** Below this the page would be a list of coincidences. */
const MIN_SHARED = 20;

const manifest = await readFile(path.join(ROOT, 'src/lib/data/most-common-words.ts'), 'utf8');
const langs = [...manifest.matchAll(/code: '([^']+)', slug: '([^']+)', name: "([^"]+)"/g)].map(
	(m) => ({ code: m[1], slug: m[2], name: m[3] })
);

const lists = new Map<string, Map<string, { rank: number; gloss: string }>>();
for (const l of langs) {
	const map = new Map<string, { rank: number; gloss: string }>();
	for (const line of (await readFile(path.join(DATA, `${l.slug}.tsv`), 'utf8'))
		.split('\n')
		.slice(1)) {
		if (!line) continue;
		const [rank, word, gloss] = line.split('\t');
		if (Number(rank) > DEPTH) break;
		map.set(word.toLowerCase(), { rank: Number(rank), gloss });
	}
	lists.set(l.code, map);
}

await mkdir(OUT, { recursive: true });
const rows: { a: string; b: string; slug: string; count: number }[] = [];

for (let i = 0; i < langs.length; i++) {
	for (let j = i + 1; j < langs.length; j++) {
		const A = lists.get(langs[i].code) as Map<string, { rank: number; gloss: string }>;
		const B = lists.get(langs[j].code) as Map<string, { rank: number; gloss: string }>;
		const shared: string[] = [];
		for (const [word, a] of A) {
			const b = B.get(word);
			if (!b || b.gloss !== a.gloss) continue;
			shared.push(`${word}\t${a.rank}\t${b.rank}\t${a.gloss}`);
		}
		if (shared.length < MIN_SHARED) continue;
		const slug = `${langs[i].slug}-and-${langs[j].slug}`;
		await writeFile(
			path.join(OUT, `${slug}.tsv`),
			`word\trank_a\trank_b\tenglish\n${shared.join('\n')}\n`
		);
		rows.push({ a: langs[i].code, b: langs[j].code, slug, count: shared.length });
	}
}

rows.sort((x, y) => y.count - x.count);

await writeFile(
	path.join(ROOT, 'src/lib/data/language-pairs.ts'),
	`// GENERATED by scripts/wordlists/build-pairs.ts — do not edit by hand.\n` +
		`// Pairs whose commonest words overlap in both spelling and meaning.\n\n` +
		`export interface LanguagePair {\n\ta: string\n\tb: string\n\tslug: string\n` +
		`\t/** Words spelled and glossed identically in both, within the top 2,000. */\n\tcount: number\n}\n\n` +
		`export const LANGUAGE_PAIRS: LanguagePair[] = [\n` +
		rows
			.map((r) => `\t{ a: '${r.a}', b: '${r.b}', slug: '${r.slug}', count: ${r.count} }`)
			.join(',\n') +
		`\n]\n`
);

console.log(`${rows.length} pairs clear ${MIN_SHARED} shared words`);
console.log(
	rows
		.slice(0, 12)
		.map((r) => `  ${r.a}/${r.b}: ${r.count}`)
		.join('\n')
);
