/**
 * Data for the three games under /tools.
 *
 *   node scripts/wordlists/build-games.ts
 *
 * Reads the word lists that are already here; downloads nothing.
 *
 *  - `games/word/<slug>.json` — the five-letter daily game: a pool of answers
 *    drawn from the commonest words, a wider set of accepted guesses, and the
 *    language's own letters for the on-screen keyboard.
 *  - `games/languages.json` — words that occur in exactly one of the 53 lists,
 *    which is what makes "which language is this?" a fair question rather than
 *    a trick.
 *
 * The meaning quiz needs no file: the language page already fetches its list,
 * and the wrong answers are other glosses from the same list.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '../..');
const DATA = path.join(ROOT, 'static/data/most-common-words');
const OUT = path.join(DATA, 'games');

/**
 * Only scripts where one character is one letter. An abugida writes a vowel as
 * a mark on a consonant and an abjad leaves it out, so "five letters" is not a
 * question either of them can be asked; Han and Hangul are further still.
 */
const ALPHABETIC = new Set(['Latin', 'Cyrillic', 'Greek', 'Armenian', 'Georgian']);

const LENGTH = 5;
/** Answers come from here — a word nobody has met is a bad puzzle. */
const ANSWER_DEPTH = 2500;
/** Guesses may come from the whole list, so a fair try is not refused. */
const GUESS_DEPTH = 10000;
/** Below this the pool repeats within a year. */
const MIN_ANSWERS = 120;

const cfg = await readFile(path.join(ROOT, 'scripts/wordlists/languages.ts'), 'utf8');
const scriptOf: Record<string, string> = {};
for (const m of cfg.matchAll(
	/\['([a-z]{2})', '[^']*', '[^']*', '[^']*', '[^']*', '([A-Za-z]+)'\]/g
)) {
	scriptOf[m[1]] = m[2];
}

const manifest = await readFile(path.join(ROOT, 'src/lib/data/most-common-words.ts'), 'utf8');
const langs = [...manifest.matchAll(/code: '([^']+)', slug: '([^']+)', name: "([^"]+)"/g)].map(
	(m) => ({ code: m[1], slug: m[2], name: m[3] })
);

await mkdir(path.join(OUT, 'word'), { recursive: true });

const isWord = (w: string) => [...w].length === LENGTH && !/[^\p{L}]/u.test(w);
const wordGame: { code: string; slug: string; name: string; answers: number }[] = [];
/** word -> the languages it appears in, for the language quiz. */
const seenIn = new Map<string, Set<string>>();
const rankOf = new Map<string, number>();

for (const lang of langs) {
	const rows = (await readFile(path.join(DATA, `${lang.slug}.tsv`), 'utf8'))
		.split('\n')
		.slice(1)
		.filter(Boolean)
		.map((line) => line.split('\t'));

	for (const [rank, word] of rows) {
		if (Number(rank) > 3000) break;
		const key = word.toLowerCase();
		if (!seenIn.has(key)) seenIn.set(key, new Set());
		seenIn.get(key)?.add(lang.code);
		const prev = rankOf.get(key);
		if (prev === undefined || Number(rank) < prev) rankOf.set(key, Number(rank));
	}

	if (!ALPHABETIC.has(scriptOf[lang.code])) continue;

	const answers: string[] = [];
	const guesses: string[] = [];
	for (const [rank, word] of rows) {
		const w = word.toLowerCase();
		if (!isWord(w)) continue;
		if (Number(rank) <= GUESS_DEPTH) guesses.push(w);
		if (Number(rank) <= ANSWER_DEPTH) answers.push(w);
	}
	if (answers.length < MIN_ANSWERS) continue;

	// The keyboard is the language's own letters, taken from the words it
	// actually uses rather than from a hand-written alphabet.
	const letters = [...new Set(guesses.flatMap((w) => [...w]))].sort((a, b) =>
		a.localeCompare(b, lang.code)
	);

	await writeFile(
		path.join(OUT, 'word', `${lang.slug}.json`),
		JSON.stringify({ answers, guesses, letters })
	);
	wordGame.push({ code: lang.code, slug: lang.slug, name: lang.name, answers: answers.length });
}

// A word in exactly one language is a fair question; "no" is in eleven.
const unique: [string, string, number][] = [];
for (const [word, codes] of seenIn) {
	if (codes.size !== 1) continue;
	if ([...word].length < 3 || /[^\p{L}]/u.test(word)) continue;
	const rank = rankOf.get(word) as number;
	if (rank > 1500) continue;
	unique.push([word, [...codes][0], rank]);
}
unique.sort((a, b) => a[2] - b[2]);
await writeFile(path.join(OUT, 'languages.json'), JSON.stringify(unique.slice(0, 4000)));

await writeFile(
	path.join(ROOT, 'src/lib/data/word-game.ts'),
	`// GENERATED by scripts/wordlists/build-games.ts — do not edit by hand.\n` +
		`// Languages whose script counts one character as one letter, and that have\n` +
		`// enough five-letter words near the top of their list to play with.\n\n` +
		`export interface WordGameLanguage {\n\tcode: string\n\tslug: string\n\tname: string\n` +
		`\t/** How many possible answers — the pool a daily puzzle is drawn from. */\n\tanswers: number\n}\n\n` +
		`export const WORD_GAME_LANGUAGES: WordGameLanguage[] = [\n` +
		wordGame
			.sort((a, b) => a.name.localeCompare(b.name))
			.map(
				(l) =>
					`\t{ code: '${l.code}', slug: '${l.slug}', name: ${JSON.stringify(l.name)}, answers: ${
						l.answers
					} }`
			)
			.join(',\n') +
		`\n]\n`
);

console.log(`word game: ${wordGame.length} languages`);
console.log(`  smallest pool: ${Math.min(...wordGame.map((l) => l.answers))} answers`);
console.log(
	`language quiz: ${unique.length} words unique to one language, kept ${Math.min(
		unique.length,
		4000
	)}`
);
