/**
 * Picks the English words that get a "how to say X" page, and writes the
 * manifest the route iterates.
 *
 *   node scripts/wordlists/build-say.ts
 *
 * Everything it needs is already in the English side of the search index, so
 * this adds no data — it decides which keys are worth a page and lets the
 * route read the rows back out of the shards at prerender time.
 */
import { readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '../..');
const IDX = path.join(ROOT, 'static/data/most-common-words/idx/e');

/**
 * Below this a page is mostly gaps, and a page of gaps is the thin content
 * that drags the rest of a site down with it. At 30 of 53 the table is full
 * enough to be the answer somebody came for.
 */
const MIN_LANGUAGES = 30;

/**
 * Words that are about language rather than in it. They reach the index
 * through glosses like "alternative form of X" and would make a page that
 * answers nothing.
 */
const NOT_A_CONCEPT = new Set([
	'alternative',
	'diminutive',
	'augmentative',
	'inflection',
	'participle',
	'gerund',
	'infinitive',
	'imperative',
	'subjunctive',
	'vocative',
	'locative',
	'instrumental',
	'perfective',
	'imperfective',
	'transitive',
	'intransitive',
	'reflexive',
	'archaic',
	'obsolete',
	'colloquial',
	'informal',
	'formal',
	'literally',
	'especially',
	'typically',
	'usually',
	'often',
	'sometimes',
	'etc'
]);

const rows: { word: string; slug: string; count: number }[] = [];

for (const file of await readdir(IDX)) {
	if (!file.endsWith('.json') || file === 'stats.json') continue;
	const obj = JSON.parse(await readFile(path.join(IDX, file), 'utf8')) as Record<string, unknown[]>;
	for (const [word, hits] of Object.entries(obj)) {
		if (hits.length < MIN_LANGUAGES) continue;
		// Letters only: an index key with punctuation in it is a fragment.
		if (!/^[a-z][a-z-]*[a-z]$/.test(word)) continue;
		if (NOT_A_CONCEPT.has(word)) continue;
		rows.push({ word, slug: word, count: hits.length });
	}
}

rows.sort((a, b) => a.word.localeCompare(b.word));

await writeFile(
	path.join(ROOT, 'src/lib/data/say-words.ts'),
	`// GENERATED by scripts/wordlists/build-say.ts — do not edit by hand.\n` +
		`// The English words with a page under /tools/say. The rows themselves are\n` +
		`// read out of the search index at prerender time, not duplicated here.\n\n` +
		`export interface SayWord {\n\tword: string\n\tslug: string\n` +
		`\t/** How many languages have a word for it. Never assume 53. */\n\tcount: number\n}\n\n` +
		`export const SAY_WORDS: SayWord[] = [\n` +
		rows.map((r) => `\t{ word: '${r.word}', slug: '${r.slug}', count: ${r.count} }`).join(',\n') +
		`\n]\n`
);

console.log(`${rows.length} words qualify (${MIN_LANGUAGES}+ languages)`);
console.log(`  fullest: ${rows.filter((r) => r.count >= 50).length} in 50 or more`);
