#!/usr/bin/env bash
# Publishes static/audio/w and static/audio/x — the word and example-sentence
# readings build-word-audio.py wrote — as one GitHub release asset, which the
# deploy workflow unpacks into static/audio before it builds.
#
#   scripts/wordlists/word-audio.sh word-audio-2026-09-23
#
# Then set WORD_AUDIO_RELEASE in .github/workflows/deploy.yml to the same tag.
# A new tag for every new set of readings, rather than replacing the asset on
# an old one, so the deploy of any commit can still find the files it expects.
set -euo pipefail

tag="${1:?usage: $0 <tag>, e.g. word-audio-$(date +%F)}"
root="$(cd "$(dirname "$0")/../.." && pwd)"
src="$root/static/audio"
for store in w x; do
  test -f "$src/$store/en/index.json" || {
    echo "no readings in $src/$store — run build-word-audio.py (--sentences for x) first" >&2
    exit 1
  }
done

out="$(mktemp -d)/word-audio.tar"
# MP3 does not compress, so a plain tar: gzip would cost minutes for nothing.
# The two stores as directories at the top, so the deploy unpacks both in one.
tar -cf "$out" -C "$src" w x
ls -lh "$out"

gh release create "$tag" "$out" \
  --repo langx/website \
  --title "Word readings ($tag)" \
  --latest=false \
  --notes "Synthesised readings of the top 5,000 words of each voiced word list (w/) and of the lists' example sentences (x/), unpacked into static/audio by the deploy workflow. Generated by scripts/wordlists/build-word-audio.py with the voices of langx/apps/tts. Not a software release."
