#!/usr/bin/env bash
# Publishes static/audio/w — what build-word-audio.py wrote — as a GitHub
# release asset, which the deploy workflow unpacks before it builds.
#
#   scripts/wordlists/word-audio.sh word-audio-2026-09-23
#
# Then set WORD_AUDIO_RELEASE in .github/workflows/deploy.yml to the same tag.
# A new tag for every new set of readings, rather than replacing the asset on
# an old one, so the deploy of any commit can still find the files it expects.
set -euo pipefail

tag="${1:?usage: $0 <tag>, e.g. word-audio-$(date +%F)}"
root="$(cd "$(dirname "$0")/../.." && pwd)"
src="$root/static/audio/w"
test -f "$src/en/index.json" || { echo "no readings in $src — run build-word-audio.py first" >&2; exit 1; }

out="$(mktemp -d)/word-audio.tar"
# MP3 does not compress, so a plain tar: gzip would cost minutes for nothing.
tar -cf "$out" -C "$src" .
ls -lh "$out"

gh release create "$tag" "$out" \
  --repo langx/website \
  --title "Word readings ($tag)" \
  --latest=false \
  --notes "Synthesised readings of the top 5,000 words of each voiced word list, unpacked into static/audio/w by the deploy workflow. Generated by scripts/wordlists/build-word-audio.py with the voices of langx/apps/tts. Not a software release."
