#!/usr/bin/env bash
# Publishes static/audio/w and static/audio/x — the word and example-sentence
# readings build-word-audio.py wrote — as one GitHub release asset, which the
# deploy workflow unpacks into static/audio before it builds.
#
#   scripts/wordlists/word-audio.sh word-audio-2026-09-23
#
# Then set WORD_AUDIO_RELEASE in .github/workflows/deploy.yml to the same tag.
# A new tag for every new set of readings, rather than replacing the asset on
# an old one, so the deploy of any commit can still find the files it expects.
set -euo pipefail

tag="${1:?usage: $0 <tag>, e.g. word-audio-$(date +%F)}"
root="$(cd "$(dirname "$0")/../.." && pwd)"
src="$root/static/audio"
for store in w x; do
  test -f "$src/$store/en/index.json" || {
    echo "no readings in $src/$store — run build-word-audio.py (--sentences for x) first" >&2
    exit 1
  }
done

out="$(mktemp -d)/word-audio.tar"
# MP3 does not compress, so a plain tar: gzip would cost minutes for nothing.
# The two stores as directories at the top, so the deploy unpacks both in one.
tar -cf "$out" -C "$src" w x
ls -lh "$out"

# A draft first, then the upload, then the release: four hundred megabytes over
# one connection can time out part-way — it did on 23 September 2026, and
# `gh release create` with the file attached then deleted the whole release.
# This way a failed upload is retried against the same draft, and the tag only
# appears once the asset it names is really there.
gh release create "$tag" \
  --repo langx/website \
  --draft \
  --title "Word readings ($tag)" \
  --notes "Synthesised readings of the top 5,000 words of each voiced word list (w/) and of the lists' example sentences (x/), unpacked into static/audio by the deploy workflow. Generated by scripts/wordlists/build-word-audio.py with the voices of langx/apps/tts. Not a software release."

for attempt in 1 2 3 4 5; do
  if gh release upload "$tag" "$out" --repo langx/website --clobber; then
    gh release edit "$tag" --repo langx/website --draft=false --latest=false
    gh release view "$tag" --repo langx/website --json url --jq .url
    exit 0
  fi
  echo "upload failed (attempt $attempt), retrying in 30s" >&2
  sleep 30
done
echo "upload failed five times; the draft $tag is still there to retry" >&2
exit 1
