// GENERATED by scripts/wordlists/build-pairs.ts — do not edit by hand.
// Pairs whose commonest words overlap in both spelling and meaning.

export interface LanguagePair {
	a: string;
	b: string;
	slug: string;
	/** Words spelled and glossed identically in both, within the top 2,000. */
	count: number;
}

export const LANGUAGE_PAIRS: LanguagePair[] = [
	{ a: 'bs', b: 'sr', slug: 'bosnian-and-serbian', count: 1885 },
	{ a: 'bs', b: 'hr', slug: 'bosnian-and-croatian', count: 1811 },
	{ a: 'hr', b: 'sr', slug: 'croatian-and-serbian', count: 1728 },
	{ a: 'id', b: 'ms', slug: 'indonesian-and-malay', count: 372 },
	{ a: 'da', b: 'no', slug: 'danish-and-norwegian', count: 326 },
	{ a: 'gl', b: 'pt', slug: 'galician-and-portuguese', count: 288 },
	{ a: 'gl', b: 'es', slug: 'galician-and-spanish', count: 261 },
	{ a: 'cs', b: 'sk', slug: 'czech-and-slovak', count: 256 },
	{ a: 'bg', b: 'mk', slug: 'bulgarian-and-macedonian', count: 186 },
	{ a: 'pt', b: 'es', slug: 'portuguese-and-spanish', count: 167 },
	{ a: 'hr', b: 'sl', slug: 'croatian-and-slovenian', count: 162 },
	{ a: 'ru', b: 'uk', slug: 'russian-and-ukrainian', count: 161 },
	{ a: 'af', b: 'nl', slug: 'afrikaans-and-dutch', count: 153 },
	{ a: 'sr', b: 'sl', slug: 'serbian-and-slovenian', count: 153 },
	{ a: 'bs', b: 'sl', slug: 'bosnian-and-slovenian', count: 150 },
	{ a: 'no', b: 'sv', slug: 'norwegian-and-swedish', count: 118 },
	{ a: 'fa', b: 'ur', slug: 'persian-and-urdu', count: 107 },
	{ a: 'da', b: 'sv', slug: 'danish-and-swedish', count: 91 },
	{ a: 'ca', b: 'es', slug: 'catalan-and-spanish', count: 89 },
	{ a: 'ca', b: 'gl', slug: 'catalan-and-galician', count: 82 },
	{ a: 'ca', b: 'pt', slug: 'catalan-and-portuguese', count: 81 },
	{ a: 'bg', b: 'ru', slug: 'bulgarian-and-russian', count: 77 },
	{ a: 'sk', b: 'sl', slug: 'slovak-and-slovenian', count: 75 },
	{ a: 'mk', b: 'ru', slug: 'macedonian-and-russian', count: 62 },
	{ a: 'sr', b: 'sk', slug: 'serbian-and-slovak', count: 60 },
	{ a: 'ca', b: 'fr', slug: 'catalan-and-french', count: 58 },
	{ a: 'hr', b: 'sk', slug: 'croatian-and-slovak', count: 58 },
	{ a: 'bs', b: 'sk', slug: 'bosnian-and-slovak', count: 57 },
	{ a: 'hr', b: 'cs', slug: 'croatian-and-czech', count: 54 },
	{ a: 'bg', b: 'uk', slug: 'bulgarian-and-ukrainian', count: 53 },
	{ a: 'mk', b: 'uk', slug: 'macedonian-and-ukrainian', count: 53 },
	{ a: 'bs', b: 'cs', slug: 'bosnian-and-czech', count: 52 },
	{ a: 'cs', b: 'sr', slug: 'czech-and-serbian', count: 52 },
	{ a: 'it', b: 'es', slug: 'italian-and-spanish', count: 44 },
	{ a: 'cs', b: 'pl', slug: 'czech-and-polish', count: 42 },
	{ a: 'it', b: 'pt', slug: 'italian-and-portuguese', count: 41 },
	{ a: 'cs', b: 'sl', slug: 'czech-and-slovenian', count: 40 },
	{ a: 'nl', b: 'de', slug: 'dutch-and-german', count: 37 },
	{ a: 'gl', b: 'it', slug: 'galician-and-italian', count: 37 },
	{ a: 'pl', b: 'sk', slug: 'polish-and-slovak', count: 36 },
	{ a: 'af', b: 'de', slug: 'afrikaans-and-german', count: 31 },
	{ a: 'ca', b: 'ro', slug: 'catalan-and-romanian', count: 30 },
	{ a: 'bs', b: 'pl', slug: 'bosnian-and-polish', count: 28 },
	{ a: 'da', b: 'nl', slug: 'danish-and-dutch', count: 28 },
	{ a: 'pl', b: 'sr', slug: 'polish-and-serbian', count: 28 },
	{ a: 'hr', b: 'pl', slug: 'croatian-and-polish', count: 26 },
	{ a: 'ca', b: 'it', slug: 'catalan-and-italian', count: 25 },
	{ a: 'et', b: 'fi', slug: 'estonian-and-finnish', count: 25 },
	{ a: 'da', b: 'de', slug: 'danish-and-german', count: 23 },
	{ a: 'fr', b: 'ro', slug: 'french-and-romanian', count: 23 },
	{ a: 'it', b: 'ro', slug: 'italian-and-romanian', count: 23 },
	{ a: 'ar', b: 'fa', slug: 'arabic-and-persian', count: 21 },
	{ a: 'es', b: 'tl', slug: 'spanish-and-tagalog', count: 21 },
	{ a: 'sq', b: 'bs', slug: 'albanian-and-bosnian', count: 20 },
	{ a: 'sq', b: 'hr', slug: 'albanian-and-croatian', count: 20 }
];
