// GENERATED by scripts/wordlists/build.ts — do not edit by hand.
// One row per language that has a page under /tools/most-common-words.
// The word lists themselves are in static/data/most-common-words/.

export interface WordListMeta {
	/** ISO 639-1, matching packages/shared/src/languages.ts. */
	code: string
	/** URL segment, e.g. 'spanish'. */
	slug: string
	name: string
	nativeName: string
	/** How many words the list actually has. Not always 10,000. */
	count: number
	/** Size of the .tsv, for the download link. */
	bytes: number
	/** Percentage of rows carrying an English meaning. */
	glossCoverage: number
}

export const WORD_LISTS: WordListMeta[] = [
	{ code: 'af', slug: 'afrikaans', name: "Afrikaans", nativeName: "Afrikaans", count: 2915, bytes: 70014, glossCoverage: 100 },
	{ code: 'sq', slug: 'albanian', name: "Albanian", nativeName: "Shqip", count: 7032, bytes: 185686, glossCoverage: 100 },
	{ code: 'ar', slug: 'arabic', name: "Arabic", nativeName: "العربية", count: 7589, bytes: 286717, glossCoverage: 100 },
	{ code: 'hy', slug: 'armenian', name: "Armenian", nativeName: "Հայերեն", count: 1825, bytes: 64096, glossCoverage: 100 },
	{ code: 'eu', slug: 'basque', name: "Basque", nativeName: "euskara", count: 2924, bytes: 70773, glossCoverage: 100 },
	{ code: 'bn', slug: 'bengali', name: "Bengali", nativeName: "বাংলা", count: 3802, bytes: 145115, glossCoverage: 100 },
	{ code: 'bs', slug: 'bosnian', name: "Bosnian", nativeName: "bosanski jezik", count: 10000, bytes: 260401, glossCoverage: 100 },
	{ code: 'bg', slug: 'bulgarian', name: "Bulgarian", nativeName: "български език", count: 10000, bytes: 518828, glossCoverage: 100 },
	{ code: 'ca', slug: 'catalan', name: "Catalan", nativeName: "català", count: 10000, bytes: 268058, glossCoverage: 100 },
	{ code: 'zh', slug: 'chinese', name: "Chinese", nativeName: "中文", count: 10000, bytes: 384317, glossCoverage: 100 },
	{ code: 'hr', slug: 'croatian', name: "Croatian", nativeName: "hrvatski jezik", count: 10000, bytes: 263541, glossCoverage: 100 },
	{ code: 'cs', slug: 'czech', name: "Czech", nativeName: "čeština", count: 10000, bytes: 247517, glossCoverage: 100 },
	{ code: 'da', slug: 'danish', name: "Danish", nativeName: "dansk", count: 10000, bytes: 263113, glossCoverage: 100 },
	{ code: 'nl', slug: 'dutch', name: "Dutch", nativeName: "Nederlands", count: 10000, bytes: 313480, glossCoverage: 100 },
	{ code: 'en', slug: 'english', name: "English", nativeName: "English", count: 10000, bytes: 576810, glossCoverage: 100 },
	{ code: 'eo', slug: 'esperanto', name: "Esperanto", nativeName: "Esperanto", count: 10000, bytes: 273449, glossCoverage: 100 },
	{ code: 'et', slug: 'estonian', name: "Estonian", nativeName: "eesti", count: 5619, bytes: 142340, glossCoverage: 100 },
	{ code: 'fi', slug: 'finnish', name: "Finnish", nativeName: "suomi", count: 10000, bytes: 325317, glossCoverage: 100 },
	{ code: 'fr', slug: 'french', name: "French", nativeName: "français", count: 10000, bytes: 284955, glossCoverage: 100 },
	{ code: 'gl', slug: 'galician', name: "Galician", nativeName: "Galego", count: 10000, bytes: 264032, glossCoverage: 100 },
	{ code: 'ka', slug: 'georgian', name: "Georgian", nativeName: "ქართული", count: 1550, bytes: 64654, glossCoverage: 100 },
	{ code: 'de', slug: 'german', name: "German", nativeName: "Deutsch", count: 10000, bytes: 317110, glossCoverage: 100 },
	{ code: 'el', slug: 'greek', name: "Greek", nativeName: "Ελληνικά", count: 10000, bytes: 391533, glossCoverage: 100 },
	{ code: 'he', slug: 'hebrew', name: "Hebrew", nativeName: "עברית", count: 6856, bytes: 253736, glossCoverage: 100 },
	{ code: 'hi', slug: 'hindi', name: "Hindi", nativeName: "हिन्दी", count: 8906, bytes: 367246, glossCoverage: 100 },
	{ code: 'hu', slug: 'hungarian', name: "Hungarian", nativeName: "magyar", count: 10000, bytes: 338653, glossCoverage: 100 },
	{ code: 'is', slug: 'icelandic', name: "Icelandic", nativeName: "Íslenska", count: 7439, bytes: 202632, glossCoverage: 100 },
	{ code: 'id', slug: 'indonesian', name: "Indonesian", nativeName: "Bahasa Indonesia", count: 10000, bytes: 348284, glossCoverage: 100 },
	{ code: 'it', slug: 'italian', name: "Italian", nativeName: "Italiano", count: 10000, bytes: 323540, glossCoverage: 100 },
	{ code: 'ko', slug: 'korean', name: "Korean", nativeName: "한국어", count: 5927, bytes: 177556, glossCoverage: 100 },
	{ code: 'lv', slug: 'latvian', name: "Latvian", nativeName: "latviešu valoda", count: 10000, bytes: 345692, glossCoverage: 100 },
	{ code: 'lt', slug: 'lithuanian', name: "Lithuanian", nativeName: "lietuvių kalba", count: 5942, bytes: 166231, glossCoverage: 100 },
	{ code: 'mk', slug: 'macedonian', name: "Macedonian", nativeName: "македонски јазик", count: 10000, bytes: 335011, glossCoverage: 100 },
	{ code: 'ms', slug: 'malay', name: "Malay", nativeName: "Bahasa Melayu", count: 5228, bytes: 158404, glossCoverage: 100 },
	{ code: 'ml', slug: 'malayalam', name: "Malayalam", nativeName: "മലയാളം", count: 3457, bytes: 133743, glossCoverage: 100 },
	{ code: 'no', slug: 'norwegian', name: "Norwegian", nativeName: "Norsk", count: 10000, bytes: 267623, glossCoverage: 100 },
	{ code: 'fa', slug: 'persian', name: "Persian", nativeName: "فارسی", count: 7118, bytes: 217343, glossCoverage: 100 },
	{ code: 'pl', slug: 'polish', name: "Polish", nativeName: "język polski", count: 10000, bytes: 293067, glossCoverage: 100 },
	{ code: 'pt', slug: 'portuguese', name: "Portuguese", nativeName: "Português", count: 10000, bytes: 291444, glossCoverage: 100 },
	{ code: 'ro', slug: 'romanian', name: "Romanian", nativeName: "Română", count: 10000, bytes: 253751, glossCoverage: 100 },
	{ code: 'ru', slug: 'russian', name: "Russian", nativeName: "Русский", count: 10000, bytes: 543680, glossCoverage: 100 },
	{ code: 'sr', slug: 'serbian', name: "Serbian", nativeName: "српски језик", count: 10000, bytes: 259945, glossCoverage: 100 },
	{ code: 'sk', slug: 'slovak', name: "Slovak", nativeName: "slovenčina", count: 5106, bytes: 117457, glossCoverage: 100 },
	{ code: 'sl', slug: 'slovenian', name: "Slovenian", nativeName: "slovenski jezik", count: 3076, bytes: 70804, glossCoverage: 100 },
	{ code: 'es', slug: 'spanish', name: "Spanish", nativeName: "Español", count: 10000, bytes: 291977, glossCoverage: 100 },
	{ code: 'sv', slug: 'swedish', name: "Swedish", nativeName: "Svenska", count: 10000, bytes: 322353, glossCoverage: 100 },
	{ code: 'tl', slug: 'tagalog', name: "Tagalog", nativeName: "Wikang Tagalog", count: 3068, bytes: 101108, glossCoverage: 100 },
	{ code: 'ta', slug: 'tamil', name: "Tamil", nativeName: "தமிழ்", count: 2201, bytes: 97386, glossCoverage: 100 },
	{ code: 'te', slug: 'telugu', name: "Telugu", nativeName: "తెలుగు", count: 1994, bytes: 92275, glossCoverage: 100 },
	{ code: 'tr', slug: 'turkish', name: "Turkish", nativeName: "Türkçe", count: 10000, bytes: 301584, glossCoverage: 100 },
	{ code: 'uk', slug: 'ukrainian', name: "Ukrainian", nativeName: "Українська", count: 10000, bytes: 512861, glossCoverage: 100 },
	{ code: 'ur', slug: 'urdu', name: "Urdu", nativeName: "اردو", count: 2568, bytes: 80631, glossCoverage: 100 },
	{ code: 'vi', slug: 'vietnamese', name: "Vietnamese", nativeName: "Tiếng Việt", count: 4921, bytes: 156955, glossCoverage: 100 }
]

export const totalWords = WORD_LISTS.reduce((n, l) => n + l.count, 0)
