// GENERATED by scripts/wordlists/build-games.ts — do not edit by hand.
// Languages whose script counts one character as one letter, and that have
// enough five-letter words near the top of their list to play with.

export interface WordGameLanguage {
	code: string;
	slug: string;
	name: string;
	/** How many possible answers — the pool a daily puzzle is drawn from. */
	answers: number;
}

export const WORD_GAME_LANGUAGES: WordGameLanguage[] = [
	{ code: 'af', slug: 'afrikaans', name: 'Afrikaans', answers: 428 },
	{ code: 'sq', slug: 'albanian', name: 'Albanian', answers: 568 },
	{ code: 'hy', slug: 'armenian', name: 'Armenian', answers: 353 },
	{ code: 'eu', slug: 'basque', name: 'Basque', answers: 479 },
	{ code: 'bs', slug: 'bosnian', name: 'Bosnian', answers: 609 },
	{ code: 'bg', slug: 'bulgarian', name: 'Bulgarian', answers: 534 },
	{ code: 'ca', slug: 'catalan', name: 'Catalan', answers: 505 },
	{ code: 'hr', slug: 'croatian', name: 'Croatian', answers: 602 },
	{ code: 'cs', slug: 'czech', name: 'Czech', answers: 657 },
	{ code: 'da', slug: 'danish', name: 'Danish', answers: 556 },
	{ code: 'nl', slug: 'dutch', name: 'Dutch', answers: 420 },
	{ code: 'en', slug: 'english', name: 'English', answers: 554 },
	{ code: 'eo', slug: 'esperanto', name: 'Esperanto', answers: 544 },
	{ code: 'et', slug: 'estonian', name: 'Estonian', answers: 641 },
	{ code: 'fi', slug: 'finnish', name: 'Finnish', answers: 482 },
	{ code: 'fr', slug: 'french', name: 'French', answers: 454 },
	{ code: 'gl', slug: 'galician', name: 'Galician', answers: 576 },
	{ code: 'ka', slug: 'georgian', name: 'Georgian', answers: 283 },
	{ code: 'de', slug: 'german', name: 'German', answers: 471 },
	{ code: 'el', slug: 'greek', name: 'Greek', answers: 485 },
	{ code: 'hu', slug: 'hungarian', name: 'Hungarian', answers: 541 },
	{ code: 'is', slug: 'icelandic', name: 'Icelandic', answers: 679 },
	{ code: 'id', slug: 'indonesian', name: 'Indonesian', answers: 501 },
	{ code: 'it', slug: 'italian', name: 'Italian', answers: 490 },
	{ code: 'lv', slug: 'latvian', name: 'Latvian', answers: 601 },
	{ code: 'lt', slug: 'lithuanian', name: 'Lithuanian', answers: 478 },
	{ code: 'mk', slug: 'macedonian', name: 'Macedonian', answers: 545 },
	{ code: 'ms', slug: 'malay', name: 'Malay', answers: 627 },
	{ code: 'no', slug: 'norwegian', name: 'Norwegian', answers: 563 },
	{ code: 'pl', slug: 'polish', name: 'Polish', answers: 497 },
	{ code: 'pt', slug: 'portuguese', name: 'Portuguese', answers: 544 },
	{ code: 'ro', slug: 'romanian', name: 'Romanian', answers: 521 },
	{ code: 'ru', slug: 'russian', name: 'Russian', answers: 475 },
	{ code: 'sr', slug: 'serbian', name: 'Serbian', answers: 626 },
	{ code: 'sk', slug: 'slovak', name: 'Slovak', answers: 659 },
	{ code: 'sl', slug: 'slovenian', name: 'Slovenian', answers: 626 },
	{ code: 'es', slug: 'spanish', name: 'Spanish', answers: 515 },
	{ code: 'sv', slug: 'swedish', name: 'Swedish', answers: 551 },
	{ code: 'tl', slug: 'tagalog', name: 'Tagalog', answers: 472 },
	{ code: 'tr', slug: 'turkish', name: 'Turkish', answers: 664 },
	{ code: 'uk', slug: 'ukrainian', name: 'Ukrainian', answers: 523 },
	{ code: 'vi', slug: 'vietnamese', name: 'Vietnamese', answers: 225 }
];
